"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import { useParams, useRouter } from "next/navigation";
import { useProjectStore } from "@/lib/store/projectStore";
import { usePipeline, AudioOptions } from "@/hooks/usePipeline";
import { Navbar } from "@/components/layout/navbar";
import { PipelineStepper } from "@/components/layout/pipeline-stepper";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import {
  ArrowLeft,
  ArrowRight,
  RefreshCw,
  Download,
  Play,
  Pause,
  Edit3,
  CheckCircle2,
  Loader2,
  FileText,
  Music,
  Subtitles,
  Video,
  Sparkles,
  AlertCircle,
  Save,
} from "lucide-react";
import {
  PipelineStep,
  Scene,
  SubtitleEntry,
  Tone,
  VoiceEmotion,
  VisualStyle,
  Platform,
} from "@/lib/types";
import { VISUAL_STYLES, VOICES, VOICE_EMOTIONS } from "@/lib/constants";
import { generateId } from "@/lib/utils";
import { TimelineEditor } from "@/components/video/timeline-editor";

// Subtitle adalah dependency internal dari Video — bukan destination step.
// UX final: Script → Audio → Video. Export sudah tidak jadi step UI.
type EditorTab = "script" | "audio" | "video";

// Konfigurasi platform tujuan + durasi (di-set di step render/Video).
const PLATFORM_CONFIG = {
  tiktok: { label: "TikTok", description: "Video vertikal 9:16", durations: ["15 detik", "30 detik", "60 detik"], defaultDuration: "30 detik" },
  youtube: { label: "YouTube", description: "Video horizontal 16:9", durations: ["1 menit", "3 menit", "5 menit", "10 menit"], defaultDuration: "3 menit" },
  reels: { label: "Instagram Reels", description: "Video vertikal 9:16", durations: ["15 detik", "30 detik", "60 detik", "90 detik"], defaultDuration: "30 detik" },
  podcast: { label: "Podcast", description: "Audio saja", durations: ["5 menit", "10 menit", "30 menit"], defaultDuration: "10 menit" },
} as const;

/** Konversi label durasi (mis. "30 detik", "3 menit") ke detik */
function durationLabelToSeconds(label: string): number {
  const match = label.match(/(\d+)\s*(detik|menit)/);
  if (!match) return 60;
  const value = parseInt(match[1], 10);
  return match[2] === "menit" ? value * 60 : value;
}

export default function ProjectEditorPage() {
  const params = useParams();
  const router = useRouter();
  const projectId = params.projectId as string;
  const {
    currentProject,
    setCurrentProject,
    loadProjects,
  } = useProjectStore();
  const { progress, generateStep, previewAudio } = usePipeline();
  const [audioOptions, setAudioOptions] = useState<AudioOptions>({
    provider: "cartesia",
    lang: "id",
    slow: false,
    voice_id: "",
    speed: 1.0,
    emotion: "",
    stability: 0.5,
    similarity_boost: 0.75,
    style: 0.5,
    use_speaker_boost: true,
  });
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [isPreviewLoading, setIsPreviewLoading] = useState(false);
  const [activeTab, setActiveTab] = useState<EditorTab>("script");
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [loadError, setLoadError] = useState<string | null>(null);

  useEffect(() => {
    loadProjects();
    setCurrentProject(projectId);

    // Timeout: if project not found after 5 seconds, show error
    const timeout = setTimeout(() => {
      const project = useProjectStore.getState().projects.find(p => p.id === projectId);
      if (!project) {
        setLoadError(`Project dengan ID "${projectId}" tidak ditemukan di store. Pastikan project sudah dibuat sebelum navigasi ke halaman ini.`);
      }
    }, 5000);

    return () => clearTimeout(timeout);
  }, [projectId, loadProjects, setCurrentProject]);

  // Auto-generate script when entering Step-by-Step mode
  useEffect(() => {
    // Project lama (legacy) bisa punya audio/subtitle tapi projects.script NULL.
    // Jika sudah ada hasil pipeline turunan, JANGAN auto-generate script —
    // biarkan user regenerate manual. Ini mencegah script lama di-overwrite.
    const hasDerivedPipelineData =
      Boolean(currentProject?.audio?.url) ||
      Boolean(currentProject?.subtitle?.url);

    if (
      currentProject &&
      !hasAutoGenerated &&
      currentProject.mode === "step-by-step" &&
      currentProject.steps.script === "pending" &&
      !hasDerivedPipelineData &&
      !progress.isRunning
    ) {
      setHasAutoGenerated(true);
      // Langsung tampilkan tab Script + status generating, bukan menunggu API selesai.
      setActiveTab("script");
      generateStep("script", projectId).then(() => {
        setActiveTab("script");
      });
    } else if (
      currentProject &&
      currentProject.steps.script === "pending" &&
      hasDerivedPipelineData
    ) {
      // Logging sementara — project legacy dengan data turunan, skip auto-generate.
      console.log(
        `[Pipeline] Skip auto-generate script: legacy project has derived data (audio/subtitle)`
      );
    }
  }, [currentProject, hasAutoGenerated, progress.isRunning, generateStep, projectId]);

  if (!currentProject) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <div className="container mx-auto px-4 py-16 text-center">
          <Loader2 className="h-8 w-8 animate-spin mx-auto mb-4" />
          <p className="text-muted-foreground">Memuat project...</p>
        </div>
      </div>
    );
  }

  const handleGenerateStep = async (step: PipelineStep, opts?: AudioOptions) => {
    // Langsung tampilkan step yang sedang dijalankan ke user (responsif, bukan menunggu API selesai).
    // Subtitle adalah dependency internal → jangan dikunci sebagai tab tujuan.
    if (step !== "subtitle") {
      setActiveTab(step as EditorTab);
    }
    await generateStep(step, projectId, opts);
  };

  const handlePreviewAudio = async () => {
    setIsPreviewLoading(true);
    try {
      const result = await previewAudio(projectId, audioOptions);
      if (result) {
        setPreviewUrl(result);
      }
    } catch (err) {
      console.error("[AudioPanel] Preview gagal:", err);
    } finally {
      setIsPreviewLoading(false);
    }
  };

  const handleApproveStep = (step: PipelineStep) => {
    // Subtitle adalah dependency internal — bukan destination step.
    // UX final: Script → Audio → Video. Setelah video selesai user download langsung.
    const stepOrder: PipelineStep[] = ["script", "audio", "video"];
    const currentIndex = stepOrder.indexOf(step);
    if (currentIndex < stepOrder.length - 1) {
      const nextStep = stepOrder[currentIndex + 1];
      setActiveTab(nextStep as EditorTab);
      useProjectStore.getState().advanceStep(step);
      // MODE STEP-BY-STEP: HANYA pindah tab, TIDAK generate otomatis.
      // User harus klik tombol generate secara manual di tab berikutnya.
    }
  };

  const handleTabChange = (tab: EditorTab) => {
    setActiveTab(tab);
  };

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="container mx-auto px-4 py-6 lg:px-8">
        {/* Header */}
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <Button variant="ghost" size="icon" onClick={() => router.push("/")}>
              <ArrowLeft className="h-5 w-5" />
            </Button>
            <div className="min-w-0">
              <h1 className="text-xl font-bold truncate">{currentProject.title}</h1>
              <div className="flex items-center gap-2 text-xs text-muted-foreground">
                <Badge variant="outline">{currentProject.genre}</Badge>
                <span className="hidden sm:inline">{currentProject.platform}</span>
                <span className="hidden sm:inline">•</span>
                <span className="hidden sm:inline">Step by Step</span>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            {currentProject.status === "completed" && currentProject.video?.url && (
              <a
                href={currentProject.video.url}
                download={`${currentProject.title || "video"}.mp4`}
                className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
              >
                <Download className="h-4 w-4" />
                Download Video
              </a>
            )}
          </div>
        </div>

        {/* Pipeline Stepper */}
        <PipelineStepper
          currentStep={currentProject.currentStep}
          steps={currentProject.steps}
        />

        {/* Tabs (only show script/audio/video, not export) */}
        {/* Subtitle adalah dependency internal dari Video — bukan tab terpisah */}
        <div className="flex gap-1 mb-6 border-b overflow-x-auto">
          {(["script", "audio", "video"] as EditorTab[]).map((tab) => {
            const icons: Record<EditorTab, typeof FileText> = {
              script: FileText,
              audio: Music,
              video: Video,
            };
            const labels: Record<EditorTab, string> = {
              script: "Script",
              audio: "Audio",
              video: "Video",
            };
            const Icon = icons[tab];
            const stepStatus = currentProject.steps[tab];
            const isDisabled =
              tab !== "script" &&
              currentProject.steps["script"] !== "done" &&
              tab !== currentProject.currentStep;

            return (
              <button
                key={tab}
                onClick={() => handleTabChange(tab)}
                disabled={isDisabled}
                className={`flex items-center gap-2 px-3 py-2.5 text-sm font-medium border-b-2 transition-all whitespace-nowrap ${
                  activeTab === tab
                    ? "border-primary text-primary"
                    : "border-transparent text-muted-foreground hover:text-foreground"
                } ${isDisabled ? "opacity-40 cursor-not-allowed" : ""}`}
              >
                <Icon className="h-4 w-4" />
                <span className="hidden md:inline">{labels[tab]}</span>
                {stepStatus === "done" && (
                  <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500 shrink-0" />
                )}
                {stepStatus === "generating" && (
                  <Loader2 className="h-3.5 w-3.5 animate-spin text-amber-500 shrink-0" />
                )}
              </button>
            );
          })}
        </div>

        {/* Tab Content */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Preview panel (2/3 width on desktop) */}
          <div className="lg:col-span-2 space-y-4">
            {activeTab === "script" && (
              <ScriptPanel
                script={currentProject.script || null}
                isGenerating={progress.isRunning && progress.currentStep === "script"}
                progress={progress.progress}
                onGenerate={() => handleGenerateStep("script")}
                onApprove={() => handleApproveStep("script")}
              />
            )}
            {activeTab === "audio" && (
              <AudioPanel
                audio={currentProject.audio || null}
                isGenerating={progress.isRunning && progress.currentStep === "audio"}
                progress={progress.progress}
                options={audioOptions}
                setOptions={setAudioOptions}
                previewUrl={previewUrl}
                isPreviewLoading={isPreviewLoading}
                onPreview={handlePreviewAudio}
                onGenerate={() => handleGenerateStep("audio", audioOptions)}
                onApprove={() => handleApproveStep("audio")}
              />
            )}
            {activeTab === "video" && (
              <VideoPanel
                video={currentProject.video || null}
                project={currentProject}
                isGenerating={progress.isRunning && progress.currentStep === "video"}
                progress={progress.progress}
                onGenerate={() => handleGenerateStep("video")}
                onApprove={() => handleApproveStep("video")}
              />
            )}
          </div>

          {/* Control panel (1/3 width on desktop) */}
          <div className="space-y-4">
            <Card>
              <CardHeader>
                <CardTitle className="text-sm">Status Pipeline</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                {(["script", "audio", "subtitle", "video"] as PipelineStep[]).map((step) => {
                  const labels: Record<string, string> = {
                    script: "Script",
                    audio: "Audio",
                    subtitle: "Subtitle (auto)",
                    video: "Video",
                  };
                  const status = currentProject.steps[step];
                  return (
                    <div key={step} className="flex items-center justify-between text-sm">
                      <span>{labels[step]}</span>
                      <Badge
                        variant={
                          status === "done"
                            ? "success"
                            : status === "generating"
                            ? "warning"
                            : status === "error"
                            ? "destructive"
                            : "secondary"
                        }
                      >
                        {status === "done"
                          ? "Selesai"
                          : status === "generating"
                          ? "Memproses"
                          : status === "error"
                          ? "Error"
                          : "Menunggu"}
                      </Badge>
                    </div>
                  );
                })}
              </CardContent>
            </Card>

            {progress.error && (
              <Card className="border-destructive">
                <CardContent className="flex items-start gap-2 p-4 text-sm text-destructive">
                  <AlertCircle className="h-4 w-4 mt-0.5 shrink-0" />
                  <span>{progress.error}</span>
                </CardContent>
              </Card>
            )}

            {currentProject.status === "completed" && currentProject.video?.url && (
              <Card>
                <CardContent className="p-4">
                  <a
                    href={currentProject.video.url}
                    download={`${currentProject.title || "video"}.mp4`}
                    className="flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-4 py-3 text-sm font-medium text-primary-foreground hover:bg-primary/90"
                  >
                    <Download className="h-4 w-4" />
                    Download Video
                  </a>
                </CardContent>
              </Card>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}

// ============================================================
// Script Panel (with Edit Mode)
// ============================================================
function ScriptPanel({
  script,
  isGenerating,
  progress,
  onGenerate,
  onApprove,
}: {
  script: any;
  isGenerating: boolean;
  progress: number;
  onGenerate: () => void;
  onApprove: () => void;
}) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedFullScript, setEditedFullScript] = useState("");
  const [saveError, setSaveError] = useState<string | null>(null);

  // Sync edited text when script changes
  useEffect(() => {
    if (script && !isEditing) {
      setEditedFullScript(script.fullScript || "");
    }
  }, [script, isEditing]);

  const handleSaveEdit = async () => {
    if (!script) return;
    setSaveError(null);

    // Update the script with edited content
    const updatedScript = {
      ...script,
      fullScript: editedFullScript,
      scenes: parseScenesFromScript(editedFullScript, script.scenes),
    };

    // 1. Update Zustand state (client)
    useProjectStore.getState().setScriptResult(updatedScript);

    // 2. Persist ke database via PATCH /api/projects
    const project = useProjectStore.getState().currentProject;
    if (!project) {
      setSaveError("Project tidak ditemukan. Perubahan hanya tersimpan di sesi ini.");
      return;
    }

    try {
      const res = await fetch("/api/projects", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          projectId: project.id,
          script: updatedScript,
        }),
      });
      const json = await res.json();
      if (!res.ok || !json.success) {
        // Jangan hapus perubahan lokal — tampilkan error jelas
        setSaveError(json.error || `Gagal menyimpan script (HTTP ${res.status})`);
        return;
      }
    } catch (err) {
      // Jangan hapus perubahan lokal — tampilkan error jelas
      setSaveError(err instanceof Error ? err.message : "Gagal menyimpan script ke database");
      return;
    }

    setIsEditing(false);
  };

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="text-lg">Script Generator</CardTitle>
        <div className="flex items-center gap-2">
          {script && !isEditing && (
            <>
              <Button variant="outline" size="sm" onClick={() => setIsEditing(true)} className="gap-1">
                <Edit3 className="h-3.5 w-3.5" />
                Edit
              </Button>
              <Button variant="outline" size="sm" onClick={onGenerate} disabled={isGenerating} className="gap-1">
                <RefreshCw className="h-3.5 w-3.5" />
                Regenerate
              </Button>
            </>
          )}
          {isEditing && (
            <Button size="sm" onClick={handleSaveEdit} className="gap-1">
              <Save className="h-3.5 w-3.5" />
              Simpan
            </Button>
          )}
          {!script && !isGenerating && (
            <Button size="sm" onClick={onGenerate} className="gap-1">
              <Sparkles className="h-3.5 w-3.5" />
              Generate Script
            </Button>
          )}
        </div>
      </CardHeader>
      <CardContent>
        {isGenerating ? (
          <div className="space-y-4 py-8">
            <div className="flex items-center justify-center">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
            <div className="space-y-2">
              <Progress value={progress} className="h-2" />
              <p className="text-center text-sm text-muted-foreground">Menulis script...</p>
            </div>
          </div>
        ) : script ? (
          <div className="space-y-4">
            {isEditing ? (
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <h3 className="font-semibold">{script.title}</h3>
                  <Badge variant="warning">Mode Edit</Badge>
                </div>
                <textarea
                  value={editedFullScript}
                  onChange={(e) => setEditedFullScript(e.target.value)}
                  className="w-full h-80 p-3 rounded-lg border border-input bg-background text-sm font-mono resize-y"
                />
                <p className="text-xs text-muted-foreground">
                  Edit teks script secara manual. Setiap baris baru akan menjadi scene baru.
                </p>
                {saveError && (
                  <div className="flex items-start gap-2 p-3 rounded-lg border border-destructive bg-destructive/5 text-sm text-destructive">
                    <AlertCircle className="h-4 w-4 mt-0.5 shrink-0" />
                    <span>{saveError}</span>
                  </div>
                )}
              </div>
            ) : (
              <>
                <div className="flex items-center justify-between">
                  <div className="min-w-0">
                    <h3 className="font-semibold truncate">{script.title}</h3>
                    <p className="text-xs text-muted-foreground">
                      {script.wordCount} kata • estimasi {script.estimatedDuration} detik
                    </p>
                  </div>
                  <Badge variant="success" className="shrink-0">Selesai</Badge>
                </div>
                <Separator />
                <div className="max-h-96 overflow-y-auto space-y-3">
                  {script.scenes?.map((scene: Scene) => (
                    <div key={scene.id} className="space-y-1 p-3 rounded-lg bg-muted/50">
                      <div className="flex items-center justify-between">
                        <h4 className="text-sm font-medium">{scene.heading}</h4>
                        <span className="text-xs text-muted-foreground shrink-0">{scene.duration}s</span>
                      </div>
                      <p className="text-sm text-muted-foreground">{scene.content}</p>
                      {scene.visualPrompt && (
                        <p className="text-xs text-muted-foreground/70 italic">
                          🎬 {scene.visualPrompt}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              </>
            )}
            <div className="flex justify-end pt-2">
              <Button onClick={onApprove} className="gap-2">
                <CheckCircle2 className="h-4 w-4" />
                Lanjut ke Audio
              </Button>
            </div>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <FileText className="h-12 w-12 text-muted-foreground/30 mb-4" />
            <p className="text-muted-foreground mb-2">Menulis script...</p>
            <p className="text-xs text-muted-foreground/70">
              Script akan digenerate secara otomatis
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// ============================================================
// Audio Panel (with Edit Mode)
// ============================================================
function AudioPanel({
  audio,
  isGenerating,
  progress,
  onGenerate,
  onApprove,
  options,
  setOptions,
  previewUrl,
  isPreviewLoading,
  onPreview,
}: {
  audio: any;
  isGenerating: boolean;
  progress: number;
  onGenerate: () => void;
  onApprove: () => void;
  options: AudioOptions;
  setOptions: (opts: AudioOptions) => void;
  previewUrl: string | null;
  isPreviewLoading: boolean;
  onPreview: () => void;
}) {
  const setProvider = (provider: AudioOptions["provider"]) =>
    setOptions({ ...options, provider });
  const setLang = (lang: "id" | "en") => setOptions({ ...options, lang });
  const setSlow = (slow: boolean) => setOptions({ ...options, slow });
  const setVoiceId = (voice_id: string) => setOptions({ ...options, voice_id });
  const setEmotion = (emotion: string) => setOptions({ ...options, emotion });
  const setSpeed = (speed: number) => setOptions({ ...options, speed });
  const setStability = (stability: number) => setOptions({ ...options, stability });
  const setSimilarityBoost = (similarity_boost: number) => setOptions({ ...options, similarity_boost });
  const setStyle = (style: number) => setOptions({ ...options, style });
  const setSpeakerBoost = (use_speaker_boost: boolean) => setOptions({ ...options, use_speaker_boost });
  const previewAudioRef = useRef<HTMLAudioElement>(null);
  const [isPreviewPlaying, setIsPreviewPlaying] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editVoice, setEditVoice] = useState("");
  const [editEmotion, setEditEmotion] = useState<VoiceEmotion>("netral");
  const [editSpeed, setEditSpeed] = useState(1.0);
  const audioRef = useRef<HTMLAudioElement>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  // Audio preview via proxy (server-side fetch + range support)
  const audioProxyUrl = useAudioProxyUrl(audio?.url);

  const togglePlay = () => {
    if (!audioRef.current) return;
    if (isPlaying) {
      audioRef.current.pause();
    } else {
      audioRef.current.play();
    }
    setIsPlaying(!isPlaying);
  };

  // Reset saat audio selesai
  useEffect(() => {
    const el = audioRef.current;
    if (!el) return;
    const onEnded = () => setIsPlaying(false);
    el.addEventListener("ended", onEnded);
    return () => el.removeEventListener("ended", onEnded);
  }, []);

  useEffect(() => {
    if (audio && !isEditing) {
      setEditVoice(audio.voiceName || "");
      setEditEmotion(audio.emotion || "netral");
      setEditSpeed(audio.speed || 1.0);
    }
  }, [audio, isEditing]);

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="text-lg">Audio / Text-to-Speech</CardTitle>
        <div className="flex items-center gap-2">
          {audio && !isEditing && (
            <>
              <Button variant="outline" size="sm" onClick={() => setIsEditing(true)} className="gap-1">
                <Edit3 className="h-3.5 w-3.5" />
                Edit
              </Button>
              <Button variant="outline" size="sm" onClick={onGenerate} disabled={isGenerating} className="gap-1">
                <RefreshCw className="h-3.5 w-3.5" />
                Regenerate
              </Button>
            </>
          )}
          {isEditing && (
            <Button size="sm" onClick={() => { setIsEditing(false); onGenerate(); }} className="gap-1">
              <Sparkles className="h-3.5 w-3.5" />
              Generate Ulang
            </Button>
          )}
        </div>
      </CardHeader>
      <CardContent>
        {isGenerating ? (
          <div className="space-y-4 py-8">
            <div className="flex items-center justify-center">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
            <div className="space-y-2">
              <Progress value={progress} className="h-2" />
              <p className="text-center text-sm text-muted-foreground">Membuat audio dengan AI...</p>
            </div>
          </div>
        ) : audio ? (
          <div className="space-y-4">
            {isEditing ? (
              <div className="space-y-4">
                <Badge variant="warning">Mode Edit</Badge>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Voice</label>
                  <div className="grid grid-cols-2 gap-2">
                    {VOICES.map((voice) => (
                      <button
                        key={voice.name}
                        onClick={() => setEditVoice(voice.name)}
                        className={`flex items-center gap-2 p-2 rounded-lg border text-sm transition-all ${
                          editVoice === voice.name
                            ? "border-primary bg-primary/5"
                            : "border-border hover:border-primary/50"
                        }`}
                      >
                        <Music className="h-4 w-4 text-muted-foreground" />
                        <div className="text-left">
                          <div className="font-medium text-xs">{voice.name}</div>
                          <div className="text-xs text-muted-foreground">{voice.gender}</div>
                        </div>
                      </button>
                    ))}
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Emosi</label>
                  <div className="flex flex-wrap gap-2">
                    {VOICE_EMOTIONS.map((emotion) => (
                      <button
                        key={emotion.value}
                        onClick={() => setEditEmotion(emotion.value)}
                        className={`px-2 py-1 rounded-lg text-xs border transition-all ${
                          editEmotion === emotion.value
                            ? "border-primary bg-primary/10 text-primary"
                            : "border-border"
                        }`}
                      >
                        {emotion.label}
                      </button>
                    ))}
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Kecepatan: {editSpeed}x</label>
                  <input
                    type="range"
                    min="0.5"
                    max="2.0"
                    step="0.25"
                    value={editSpeed}
                    onChange={(e) => setEditSpeed(parseFloat(e.target.value))}
                    className="w-full"
                  />
                </div>
              </div>
            ) : (
              <div className="flex items-center justify-between p-3 rounded-lg bg-muted/50">
                <div className="flex items-center gap-3 min-w-0">
                  <Music className="h-5 w-5 text-primary shrink-0" />
                  <div className="min-w-0">
                    <p className="font-medium truncate">{audio.voiceName}</p>
                    <p className="text-xs text-muted-foreground">
                      {audio.provider === "elevenlabs"
                        ? "ElevenLabs"
                        : audio.provider === "cartesia"
                        ? "Cartesia"
                        : "Google TTS"}
                    </p>
                    <p className="text-xs text-muted-foreground">
                      {audio.language} • {audio.speed}x • {audio.emotion}
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  {/* Audio player + Download */}
                  {/* Prioritaskan proxy URL untuk browser preview; project.audio.url tetap Supabase URL */}
                  <audio
                    ref={audioRef}
                    src={audioProxyUrl || audio.url}
                    className="hidden"
                    onError={() => console.error("[AudioPanel] Gagal decode/load audio:", audioProxyUrl || audio.url)}
                    onLoadedMetadata={() => console.log("[AudioPanel] Audio loaded metadata, duration:", audioRef.current?.duration)}
                  />
                  <Button
                    variant="outline"
                    size="icon"
                    className="h-8 w-8 rounded-full"
                    onClick={togglePlay}
                    disabled={!audio.url}
                    title="Play / Pause"
                  >
                    {isPlaying
                      ? <Pause className="h-4 w-4" />
                      : <Play className="h-4 w-4" />}
                  </Button>
                  <a
                    href={audio.url}
                    download="faza-studio-audio.mp3"
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-input text-xs font-medium hover:bg-muted/50 transition-colors"
                  >
                    <Download className="h-3.5 w-3.5" />
                    Download MP3
                  </a>
                  <Badge variant="success">Selesai</Badge>
                </div>
              </div>
            )}
            <div className="flex justify-end pt-2">
              <Button onClick={onApprove} className="gap-2">
                <CheckCircle2 className="h-4 w-4" />
                Lanjut ke Video
              </Button>
            </div>
          </div>
        ) : (
          <div className="space-y-6">
            {/* Pilih Provider */}
            <div className="space-y-2">
              <label className="text-sm font-medium">Provider Suara</label>
              <div className="grid grid-cols-3 gap-2">
                {(["cartesia", "elevenlabs", "google"] as const).map((prov) => {
                  const labels: Record<string, string> = {
                    cartesia: "Cartesia",
                    elevenlabs: "ElevenLabs",
                    google: "Google TTS",
                  };
                  return (
                    <button
                      key={prov}
                      onClick={() => setProvider(prov)}
                      className={`px-2 py-2 rounded-lg border text-sm transition-all ${
                        options.provider === prov
                          ? "border-primary bg-primary/10 text-primary"
                          : "border-border hover:border-primary/50"
                      }`}
                    >
                      {labels[prov]}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Google TTS Settings */}
            {options.provider === "google" && (
              <div className="space-y-3">
                <div className="space-y-2">
                  <label className="text-sm font-medium">Bahasa</label>
                  <select
                    className="w-full p-2 rounded-lg border border-input bg-background text-sm"
                    value={options.lang || "id"}
                    onChange={(e) => setLang(e.target.value as "id" | "en")}
                  >
                    <option value="id">Bahasa Indonesia</option>
                    <option value="en">English</option>
                  </select>
                </div>
                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    id="slowMode"
                    checked={options.slow || false}
                    onChange={(e) => setSlow(e.target.checked)}
                  />
                  <label htmlFor="slowMode" className="text-sm">Mode Lambat (slow)</label>
                </div>
                <p className="text-xs text-muted-foreground">
                  ⚠️ Google TTS memiliki kontrol kecepatan terbatas (hanya slow/normal).
                  Kualitas suara lebih robotik dibanding Cartesia/ElevenLabs.
                </p>
              </div>
            )}

            {/* Cartesia Settings */}
            {options.provider === "cartesia" && (
              <div className="space-y-3">
                <div className="space-y-2">
                  <label className="text-sm font-medium">Pilih Suara</label>
                  <select
                    className="w-full p-2 rounded-lg border border-input bg-background text-sm"
                    value={options.voice_id || ""}
                    onChange={(e) => setVoiceId(e.target.value)}
                  >
                    <option value="">Default (dari API key)</option>
                    <option value="andi">Andi</option>
                    <option value="siti">Siti</option>
                  </select>
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Speed: {(options.speed || 1.0).toFixed(1)}x</label>
                  <input
                    type="range"
                    min="0.6"
                    max="1.5"
                    step="0.1"
                    value={options.speed || 1.0}
                    onChange={(e) => setSpeed(parseFloat(e.target.value))}
                    className="w-full"
                  />
                  <div className="flex justify-between text-xs text-muted-foreground">
                    <span>0.6x (lambat)</span><span>1.5x (cepat)</span>
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Emotion (opsional)</label>
                  <select
                    className="w-full p-2 rounded-lg border border-input bg-background text-sm"
                    value={options.emotion || ""}
                    onChange={(e) => setEmotion(e.target.value)}
                  >
                    <option value="">— Tanpa emotion —</option>
                    <option value="neutral">Neutral</option>
                    <option value="calm">Calm</option>
                    <option value="angry">Angry</option>
                    <option value="sad">Sad</option>
                    <option value="scared">Scared</option>
                    <option value="curious">Curious</option>
                    <option value="mysterious">Mysterious</option>
                  </select>
                </div>
              </div>
            )}

            {/* ElevenLabs Settings */}
            {options.provider === "elevenlabs" && (
              <div className="space-y-3">
                <div className="space-y-2">
                  <label className="text-sm font-medium">Stability: {(options.stability ?? 0.5).toFixed(2)}</label>
                  <input
                    type="range"
                    min="0"
                    max="1"
                    step="0.05"
                    value={options.stability ?? 0.5}
                    onChange={(e) => setStability(parseFloat(e.target.value))}
                    className="w-full"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Similarity Boost: {(options.similarity_boost ?? 0.75).toFixed(2)}</label>
                  <input
                    type="range"
                    min="0"
                    max="1"
                    step="0.05"
                    value={options.similarity_boost ?? 0.75}
                    onChange={(e) => setSimilarityBoost(parseFloat(e.target.value))}
                    className="w-full"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Style: {(options.style ?? 0.5).toFixed(2)}</label>
                  <input
                    type="range"
                    min="0"
                    max="1"
                    step="0.05"
                    value={options.style ?? 0.5}
                    onChange={(e) => setStyle(parseFloat(e.target.value))}
                    className="w-full"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Speed: {(options.speed || 1.0).toFixed(1)}x</label>
                  <input
                    type="range"
                    min="0.5"
                    max="2"
                    step="0.1"
                    value={options.speed || 1.0}
                    onChange={(e) => setSpeed(parseFloat(e.target.value))}
                    className="w-full"
                  />
                </div>
                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    id="speakerBoost"
                    checked={options.use_speaker_boost ?? true}
                    onChange={(e) => setSpeakerBoost(e.target.checked)}
                  />
                  <label htmlFor="speakerBoost" className="text-sm">Speaker Boost</label>
                </div>
              </div>
            )}

            {/* Preview Suara */}
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={onPreview}
                  disabled={isPreviewLoading}
                  className="gap-1"
                >
                  {isPreviewLoading
                    ? <Loader2 className="h-3.5 w-3.5 animate-spin" />
                    : <Play className="h-3.5 w-3.5" />}
                  Preview Suara
                </Button>
                {previewUrl && (
                  <audio ref={previewAudioRef} src={previewUrl} className="hidden" controls />
                )}
                {previewUrl && (
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-8 w-8 rounded-full"
                    onClick={() => {
                      if (!previewAudioRef.current) return;
                      if (isPreviewPlaying) {
                        previewAudioRef.current.pause();
                      } else {
                        previewAudioRef.current.play();
                      }
                      setIsPreviewPlaying(!isPreviewPlaying);
                    }}
                  >
                    {isPreviewPlaying
                      ? <Pause className="h-4 w-4" />
                      : <Play className="h-4 w-4" />}
                  </Button>
                )}
              </div>
              <p className="text-xs text-muted-foreground">
                Preview: dengar 7 kata pertama untuk merasakan suara sebelum generate penuh.
              </p>
            </div>

            {/* Aksi */}
            <div className="flex justify-end pt-2">
              <Button onClick={onGenerate} disabled={isGenerating} className="gap-2">
                <Sparkles className="h-4 w-4" />
                Generate Audio
              </Button>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// ============================================================
// Subtitle Panel (with Edit Mode)
// ============================================================
function SubtitlePanel({
  subtitle,
  isGenerating,
  progress,
  onGenerate,
  onApprove,
}: {
  subtitle: any;
  isGenerating: boolean;
  progress: number;
  onGenerate: () => void;
  onApprove: () => void;
}) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedEntries, setEditedEntries] = useState<SubtitleEntry[]>([]);

  useEffect(() => {
    if (subtitle && !isEditing) {
      setEditedEntries(subtitle.entries || []);
    }
  }, [subtitle, isEditing]);

  const handleEditText = (id: string, newText: string) => {
    setEditedEntries((prev) =>
      prev.map((entry) => (entry.id === id ? { ...entry, text: newText } : entry))
    );
  };

  const handleSaveEdit = () => {
    if (subtitle) {
      const updatedSubtitle = {
        ...subtitle,
        entries: editedEntries,
        srtContent: generateSrtFromEntries(editedEntries),
        vttContent: generateVttFromEntries(editedEntries),
      };
      useProjectStore.getState().setSubtitleResult(updatedSubtitle);
    }
    setIsEditing(false);
  };

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="text-lg">Subtitle</CardTitle>
        <div className="flex items-center gap-2">
          {subtitle && !isEditing && (
            <>
              <Button variant="outline" size="sm" onClick={() => setIsEditing(true)} className="gap-1">
                <Edit3 className="h-3.5 w-3.5" />
                Edit
              </Button>
              <Button variant="outline" size="sm" onClick={onGenerate} disabled={isGenerating} className="gap-1">
                <RefreshCw className="h-3.5 w-3.5" />
                Regenerate
              </Button>
            </>
          )}
          {isEditing && (
            <Button size="sm" onClick={handleSaveEdit} className="gap-1">
              <Save className="h-3.5 w-3.5" />
              Simpan
            </Button>
          )}
          {!subtitle && !isGenerating && (
            <Button size="sm" onClick={onGenerate} className="gap-1">
              <Sparkles className="h-3.5 w-3.5" />
              Generate Subtitle
            </Button>
          )}
        </div>
      </CardHeader>
      <CardContent>
        {isGenerating ? (
          <div className="space-y-4 py-8">
            <div className="flex items-center justify-center">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
            <div className="space-y-2">
              <Progress value={progress} className="h-2" />
              <p className="text-center text-sm text-muted-foreground">Sinkronisasi subtitle...</p>
            </div>
          </div>
        ) : subtitle ? (
          <div className="space-y-4">
            {isEditing && <Badge variant="warning">Mode Edit</Badge>}
            <div className="max-h-60 overflow-y-auto space-y-1">
              {(isEditing ? editedEntries : subtitle.entries)?.map((entry: SubtitleEntry) => (
                <div key={entry.id} className="flex items-start gap-2 p-2 rounded text-sm hover:bg-muted/50">
                  <span className="text-xs text-muted-foreground w-12 shrink-0 font-mono">
                    {formatTime(entry.startTime)}
                  </span>
                  {isEditing ? (
                    <input
                      type="text"
                      value={editedEntries.find((e) => e.id === entry.id)?.text || entry.text}
                      onChange={(e) => handleEditText(entry.id, e.target.value)}
                      className="flex-1 px-2 py-0.5 rounded border border-input bg-background text-sm"
                    />
                  ) : (
                    <span className="flex-1">{entry.text}</span>
                  )}
                  <span className="text-xs text-muted-foreground w-12 shrink-0 text-right font-mono">
                    {formatTime(entry.endTime)}
                  </span>
                </div>
              ))}
            </div>
            <div className="flex justify-end pt-2">
              <Button onClick={onApprove} className="gap-2">
                <CheckCircle2 className="h-4 w-4" />
                Lanjut ke Video
              </Button>
            </div>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <Subtitles className="h-12 w-12 text-muted-foreground/30 mb-4" />
            <p className="text-muted-foreground mb-2">Menyiapkan subtitle...</p>
            <p className="text-xs text-muted-foreground/70">
              Subtitle akan digenerate setelah audio selesai
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// ============================================================
// Video Panel — Composition Preview (footage + audio + subtitle)
// ============================================================
function VideoPanel({
  video,
  project,
  isGenerating,
  progress,
  onGenerate,
  onApprove,
}: {
  video: any;
  project: any;
  isGenerating: boolean;
  progress: number;
  onGenerate: () => void;
  onApprove: () => void;
}) {
  const [isEditing, setIsEditing] = useState(false);
  const [editStyle, setEditStyle] = useState<VisualStyle>("stock");
  // Footage selection state
  const [footageOptions, setFootageOptions] = useState<any[]>([]);
  const [isFootageLoading, setIsFootageLoading] = useState(false);
  const [selectedFootageId, setSelectedFootageId] = useState<string | null>(
    project?.footage?.id || null
  );
  // Timeline: footage per scene
  const [sceneFootage, setSceneFootage] = useState<{ sceneId: string; videoUrl: string }[]>([]);
  const handleTimelineRender = (list: { sceneId: string; videoUrl: string }[]) => {
    setSceneFootage(list);
    onGenerate();
  };
  // Audio playback
  const audioRef = useRef<HTMLAudioElement>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [audioError, setAudioError] = useState<string | null>(null);
  // Audio preview via proxy (server-side fetch + range support)
  const audioProxyUrl = useAudioProxyUrl(project?.audio?.url);
  // Subtitle caption/style editing (localhost — tidak trigger TTS/transcription)
  const segments = project?.subtitle?.segments || [];
  const style = project?.subtitle?.style || { fontSize: 24, color: "#FFFFFF", position: "bottom" };

  useEffect(() => {
    if (video && !isEditing) {
      setEditStyle("stock");
    }
  }, [video, isEditing]);

  // Derive query visual untuk pencarian footage
  const getFootageQuery = () => {
    const sceneWithPrompt = project?.script?.scenes?.find((s: any) => s.visualPrompt);
    return sceneWithPrompt?.visualPrompt || project?.topic || "";
  };

  const handleFetchFootage = async () => {
    setIsFootageLoading(true);
    try {
      const res = await fetch("/api/footage", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          query: getFootageQuery(),
          genre: project?.genre,
          perPage: 6,
        }),
      });
      const json = await res.json();
      if (json.success && Array.isArray(json.data)) {
        setFootageOptions(json.data);
      } else if (json.error) {
        console.error("[VideoPanel] Footage error:", json.error);
      }
    } catch (err) {
      console.error("[VideoPanel] Fetch footage gagal:", err);
    } finally {
      setIsFootageLoading(false);
    }
  };

  const handleSelectFootage = (footage: any) => {
    setSelectedFootageId(footage.id);
    useProjectStore.getState().setFootageResult(footage);
  };

  const selectedFootage = project?.footage || footageOptions.find((f) => f.id === selectedFootageId);

  // Edit caption text (tidak trigger TTS — hanya update subtitle state + re-render)
  const handleEditCaption = (segId: string, newText: string) => {
    if (!project?.subtitle) return;
    const updatedSegments = segments.map((s: any) =>
      s.id === segId ? { ...s, text: newText } : s
    );
    useProjectStore.getState().setSubtitleResult({
      ...project.subtitle,
      segments: updatedSegments,
      entries: updatedSegments.map((s: any) => ({
        id: s.id, startTime: s.startTime, endTime: s.endTime, text: s.text,
      })),
    });
  };

  // Edit style dasar (tidak trigger TTS — hanya update subtitle state + re-render)
  const handleStyleChange = (patch: { fontSize?: number; color?: string; position?: "bottom" | "top" }) => {
    if (!project?.subtitle) return;
    useProjectStore.getState().setSubtitleResult({
      ...project.subtitle,
      style: { ...style, ...patch },
    });
  };

  const togglePlay = () => {
    if (!audioRef.current) return;
    if (isPlaying) audioRef.current.pause();
    else audioRef.current.play();
    setIsPlaying(!isPlaying);
  };
  useEffect(() => {
    const el = audioRef.current;
    if (!el) return;
    const onEnded = () => setIsPlaying(false);
    el.addEventListener("ended", onEnded);
    return () => el.removeEventListener("ended", onEnded);
  }, [audioRef.current]);

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle className="text-lg">Video</CardTitle>
        <div className="flex items-center gap-2">
          {video && !isEditing && (
            <>
              <Button variant="outline" size="sm" onClick={() => setIsEditing(true)} className="gap-1">
                <Edit3 className="h-3.5 w-3.5" />
                Edit
              </Button>
              <Button variant="outline" size="sm" onClick={onGenerate} disabled={isGenerating} className="gap-1">
                <RefreshCw className="h-3.5 w-3.5" />
                Regenerate
              </Button>
            </>
          )}
          {isEditing && (
            <Button size="sm" onClick={() => { setIsEditing(false); onGenerate(); }} className="gap-1">
              <Sparkles className="h-3.5 w-3.5" />
              Render Ulang
            </Button>
          )}
          {!video && !isGenerating && (
            <Button size="sm" onClick={onGenerate} className="gap-1">
              <Sparkles className="h-3.5 w-3.5" />
              Render Video
            </Button>
          )}
        </div>
      </CardHeader>
      <CardContent>
        {/* ===== PLATFORM & DURASI (target output — di-set di step render) ===== */}
        <div className="mb-4 rounded-lg border border-border p-3 space-y-3">
          <div>
            <h4 className="text-sm font-medium">Platform Tujuan</h4>
            <p className="text-xs text-muted-foreground">Tentukan orientasi & durasi output video.</p>
          </div>
          <div className="grid grid-cols-2 gap-2">
            {Object.entries(PLATFORM_CONFIG).map(([key, config]) => (
              <button
                key={key}
                onClick={() => {
                  const platform = key as Platform;
                  const dur = config.defaultDuration;
                  useProjectStore.getState().updateProjectMeta({
                    platform,
                    targetDuration: durationLabelToSeconds(dur),
                  });
                }}
                className={`rounded-lg border p-3 text-left transition-colors ${
                  project?.platform === key
                    ? "border-primary bg-primary/10 text-primary"
                    : "border-border hover:border-primary/40"
                }`}
              >
                <div className="text-sm font-medium">{config.label}</div>
                <div className="text-xs text-muted-foreground">{config.description}</div>
              </button>
            ))}
          </div>
          {project?.platform && (
            <div className="space-y-2">
              <label className="text-xs text-muted-foreground">Durasi Konten</label>
              <div className="flex flex-wrap gap-2">
                {PLATFORM_CONFIG[(project.platform) as keyof typeof PLATFORM_CONFIG]?.durations.map((dur: string) => (
                  <button
                    key={dur}
                    onClick={() => {
                      useProjectStore.getState().updateProjectMeta({ targetDuration: durationLabelToSeconds(dur) });
                    }}
                    className={`rounded-full border px-3 py-1 text-xs transition-colors ${
                      (project?.targetDuration) === durationLabelToSeconds(dur)
                        ? "border-primary bg-primary text-primary-foreground"
                        : "border-border hover:border-primary/40"
                    }`}
                  >
                    {dur}
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* ===== COMPOSITION PREVIEW: footage + audio + subtitle bersamaan ===== */}
        <div className="space-y-4 mb-4">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-medium">Composition Preview</h3>
            <Badge variant="outline">Footage + Audio + Subtitle</Badge>
          </div>

          {/* Footage preview */}
          <div className="rounded-lg overflow-hidden border border-border bg-muted/30">
            {selectedFootage?.thumbnail ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={selectedFootage.thumbnail}
                alt={selectedFootage.query || "footage"}
                className="w-full h-40 object-cover"
              />
            ) : (
              <div className="h-40 flex items-center justify-center text-muted-foreground text-sm">
                <Video className="h-8 w-8 mr-2" />
                Belum ada footage dipilih
              </div>
            )}
          </div>

          {/* Audio player */}
          {project?.audio?.url ? (
            <div className="flex items-center gap-2 p-3 rounded-lg bg-muted/50">
              <audio
                ref={audioRef}
                src={audioProxyUrl || project.audio.url}
                className="hidden"
                onError={() => setAudioError("Gagal memuat audio. Cek URL/format.")}
                onLoadedMetadata={() => setAudioError(null)}
              />
              <Button
                variant="outline"
                size="icon"
                className="h-8 w-8 rounded-full"
                onClick={togglePlay}
                disabled={!project.audio.url}
                title="Play / Pause"
              >
                {isPlaying ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}
              </Button>
              <div className="min-w-0 flex-1">
                <p className="text-sm font-medium truncate">{project.audio.voiceName || "Audio"}</p>
                <p className="text-xs text-muted-foreground">{project.audio.provider || "TTS"}</p>
              </div>
              {audioError && (
                <span className="text-xs text-destructive">{audioError}</span>
              )}
            </div>
          ) : (
            <p className="text-xs text-muted-foreground">Belum ada audio. Generate audio dulu.</p>
          )}

          {/* Subtitle segments + edit caption */}
          {segments.length > 0 ? (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <h4 className="text-xs font-medium text-muted-foreground">Subtitle / Caption</h4>
                <span className="text-xs text-muted-foreground">{segments.length} segmen</span>
              </div>
              <div className="max-h-40 overflow-y-auto space-y-1">
                {segments.map((seg: any) => (
                  <div key={seg.id} className="flex items-center gap-2 text-sm">
                    <span className="text-xs text-muted-foreground w-16 shrink-0 font-mono">
                      {formatTime(seg.startTime)}
                    </span>
                    <input
                      type="text"
                      value={seg.text}
                      onChange={(e) => handleEditCaption(seg.id, e.target.value)}
                      className="flex-1 px-2 py-1 rounded border border-input bg-background text-sm"
                    />
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <p className="text-xs text-muted-foreground">Belum ada subtitle. Generate subtitle dulu.</p>
          )}

          {/* Style dasar */}
          {project?.subtitle && (
            <div className="space-y-2 border-t pt-3">
              <h4 className="text-xs font-medium text-muted-foreground">Style Caption</h4>
              <div className="flex flex-wrap gap-3 items-center">
                <label className="text-xs">Font: {style.fontSize}</label>
                <input
                  type="range"
                  min="16"
                  max="48"
                  step="2"
                  value={style.fontSize}
                  onChange={(e) => handleStyleChange({ fontSize: parseInt(e.target.value) })}
                  className="w-24"
                />
                <select
                  value={style.color}
                  onChange={(e) => handleStyleChange({ color: e.target.value })}
                  className="px-2 py-1 rounded border border-input bg-background text-xs"
                >
                  <option value="#FFFFFF">Putih</option>
                  <option value="#000000">Hitam</option>
                  <option value="#FFD700">Kuning</option>
                </select>
                <select
                  value={style.position}
                  onChange={(e) => handleStyleChange({ position: e.target.value as "bottom" | "top" })}
                  className="px-2 py-1 rounded border border-input bg-background text-xs"
                >
                  <option value="bottom">Bawah</option>
                  <option value="top">Atas</option>
                </select>
              </div>
            </div>
          )}
        </div>

        {/* ===== TIMELINE EDITOR ===== */}
        <div className="border-t pt-4 mb-4">
          <TimelineEditor
            project={project}
            isGenerating={isGenerating}
            progress={progress}
            onRender={handleTimelineRender}
          />
        </div>

        {isGenerating ? (
          <div className="space-y-4 py-8">
            <div className="flex items-center justify-center">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
            <div className="space-y-2">
              <Progress value={progress} className="h-2" />
              <p className="text-center text-sm text-muted-foreground">
                Merender video... {Math.round(progress)}%
              </p>
            </div>
          </div>
        ) : video ? (
          <div className="space-y-4">
            {isEditing ? (
              <div className="space-y-3">
                <Badge variant="warning">Mode Edit</Badge>
                <div className="grid grid-cols-1 gap-2">
                  {VISUAL_STYLES.map((style) => (
                    <button
                      key={style.value}
                      onClick={() => setEditStyle(style.value)}
                      className={`flex items-center gap-3 p-3 rounded-lg border transition-all text-left ${
                        editStyle === style.value
                          ? "border-primary bg-primary/5"
                          : "border-border hover:border-primary/50"
                      }`}
                    >
                      <div>
                        <div className="font-medium text-sm">{style.label}</div>
                        <div className="text-xs text-muted-foreground">{style.description}</div>
                      </div>
                    </button>
                  ))}
                </div>
              </div>
            ) : (
              <div className="rounded-lg overflow-hidden border border-border bg-black">
                <video
                  src={video.url}
                  controls
                  className="w-full aspect-video object-contain"
                  poster={video.thumbnailUrl}
                />
              </div>
            )}

            {/* Ganti Footage — re-render tanpa ulang pipeline sebelumnya */}
            <div className="space-y-3 border-t pt-4">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-medium">Pilih Footage</h3>
                <Button variant="outline" size="sm" onClick={handleFetchFootage} disabled={isFootageLoading} className="gap-1">
                  {isFootageLoading ? (
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                  ) : (
                    <RefreshCw className="h-3.5 w-3.5" />
                  )}
                  Muat Opsi Footage
                </Button>
              </div>

              {selectedFootage && (
                <div className="flex items-center gap-2 text-xs text-muted-foreground">
                  <Badge variant="success">Footage Dipilih</Badge>
                  <span className="truncate">{selectedFootage.query || selectedFootage.id}</span>
                </div>
              )}

              {isFootageLoading ? (
                <div className="flex items-center justify-center gap-2 py-4 text-sm text-muted-foreground">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Mencari footage...
                </div>
              ) : footageOptions.length > 0 ? (
                <div className="grid grid-cols-3 gap-2">
                  {footageOptions.map((f) => (
                    <button
                      key={f.id}
                      onClick={() => handleSelectFootage(f)}
                      className={`relative aspect-video rounded-lg overflow-hidden border-2 transition-all ${
                        selectedFootageId === f.id
                          ? "border-primary ring-2 ring-primary/30"
                          : "border-border hover:border-primary/50"
                      }`}
                      title={f.query}
                    >
                      {/* Thumbnail */}
                      {f.thumbnail && (
                        // eslint-disable-next-line @next/next/no-img-element
                        <img
                          src={f.thumbnail}
                          alt={f.query}
                          className="w-full h-full object-cover"
                        />
                      )}
                      {/* Overlay durasi */}
                      <div className="absolute bottom-0 inset-x-0 bg-black/60 text-white text-[10px] px-1.5 py-0.5 text-right">
                        {f.duration ? `${f.duration}s` : "?"}
                      </div>
                      {/* Check icon saat terpilih */}
                      {selectedFootageId === f.id && (
                        <div className="absolute top-1 right-1 bg-primary text-primary-foreground rounded-full p-0.5">
                          <CheckCircle2 className="h-3 w-3" />
                        </div>
                      )}
                    </button>
                  ))}
                </div>
              ) : (
                <p className="text-xs text-muted-foreground">
                  Klik "Muat Opsi Footage" untuk melihat pilihan footage yang ditawarkan sistem.
                </p>
              )}
            </div>

            <div className="flex flex-wrap justify-end gap-2 pt-2">
              {project?.audio?.url && (
                <a
                  href={project.audio.url}
                  download="faza-studio-audio.mp3"
                  className="inline-flex items-center gap-2 rounded-lg border border-input px-3 py-2 text-sm font-medium hover:bg-accent"
                >
                  <Download className="h-4 w-4" />
                  Download Audio
                </a>
              )}
              {project?.video?.url && (
                <a
                  href={project.video.url}
                  download={`${project.title || "video"}.mp4`}
                  className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
                >
                  <Download className="h-4 w-4" />
                  Download Video
                </a>
              )}
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            {/* Pilih Footage sebelum render */}
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-sm font-medium">Pilih Footage</h3>
                  <p className="text-xs text-muted-foreground">
                    Pilih video background dari sistem, atau langsung render dengan rekomendasi otomatis.
                  </p>
                </div>
                <Button variant="outline" size="sm" onClick={handleFetchFootage} disabled={isFootageLoading} className="gap-1">
                  {isFootageLoading ? (
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                  ) : (
                    <RefreshCw className="h-3.5 w-3.5" />
                  )}
                  Muat Opsi Footage
                </Button>
              </div>

              {selectedFootage && (
                <div className="flex items-center gap-2 text-xs text-muted-foreground">
                  <Badge variant="success">Footage Dipilih</Badge>
                  <span className="truncate">{selectedFootage.query || selectedFootage.id}</span>
                </div>
              )}

              {isFootageLoading ? (
                <div className="flex items-center justify-center gap-2 py-4 text-sm text-muted-foreground">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Mencari footage...
                </div>
              ) : footageOptions.length > 0 ? (
                <div className="grid grid-cols-3 gap-2">
                  {footageOptions.map((f) => (
                    <button
                      key={f.id}
                      onClick={() => handleSelectFootage(f)}
                      className={`relative aspect-video rounded-lg overflow-hidden border-2 transition-all ${
                        selectedFootageId === f.id
                          ? "border-primary ring-2 ring-primary/30"
                          : "border-border hover:border-primary/50"
                      }`}
                      title={f.query}
                    >
                      {f.thumbnail && (
                        // eslint-disable-next-line @next/next/no-img-element
                        <img
                          src={f.thumbnail}
                          alt={f.query}
                          className="w-full h-full object-cover"
                        />
                      )}
                      <div className="absolute bottom-0 inset-x-0 bg-black/60 text-white text-[10px] px-1.5 py-0.5 text-right">
                        {f.duration ? `${f.duration}s` : "?"}
                      </div>
                      {selectedFootageId === f.id && (
                        <div className="absolute top-1 right-1 bg-primary text-primary-foreground rounded-full p-0.5">
                          <CheckCircle2 className="h-3 w-3" />
                        </div>
                      )}
                    </button>
                  ))}
                </div>
              ) : (
                <p className="text-xs text-muted-foreground">
                  Klik "Muat Opsi Footage" untuk melihat pilihan footage yang ditawarkan sistem.
                </p>
              )}
            </div>

            {/* Aksi render */}
            <div className="flex justify-end pt-2">
              <Button onClick={onGenerate} disabled={isGenerating} className="gap-2">
                <Sparkles className="h-4 w-4" />
                Render Video
              </Button>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// ============================================================
// Audio Proxy Helper
// ============================================================

/**
 * Prioritaskan `/api/audio-proxy?url=<encoded-supabase-url>` sebagai source audio preview.
 * project.audio.url TETAP Supabase URL untuk backend/subtitle/download.
 */
function useAudioProxyUrl(audioUrl: string | null | undefined): string | null {
  const [proxyUrl, setProxyUrl] = useState<string | null>(null);

  useEffect(() => {
    if (!audioUrl) {
      setProxyUrl(null);
      return;
    }

    // Prioritaskan proxy URL (server-side fetch + range support)
    const proxy = `/api/audio-proxy?url=${encodeURIComponent(audioUrl)}`;
    setProxyUrl(proxy);

    // Fallback: fetch → blob → object URL (hanya jika proxy gagal)
    let objectUrl: string | null = null;
    let cancelled = false;

    const tryFetchBlob = async () => {
      try {
        const res = await fetch(audioUrl);
        if (!res.ok || cancelled) return;
        const blob = await res.blob();
        if (cancelled) return;
        objectUrl = URL.createObjectURL(blob);
      } catch {
        // ignore — proxy is primary
      }
    };

    tryFetchBlob();

    return () => {
      cancelled = true;
      if (objectUrl) {
        URL.revokeObjectURL(objectUrl);
      }
    };
  }, [audioUrl]);

  return proxyUrl;
}

// ============================================================
// Helpers
// ============================================================

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${s.toString().padStart(2, "0")}`;
}

function parseScenesFromScript(fullScript: string, originalScenes: Scene[]): Scene[] {
  const lines = fullScript.split("\n\n").filter((l) => l.trim());
  if (lines.length === 0) return originalScenes;

  return lines.map((line, i) => {
    const existing = originalScenes[i];
    const parts = line.split("\n");
    const heading = parts[0] || `Bagian ${i + 1}`;
    const content = parts.slice(1).join("\n") || parts[0] || "";

    return {
      id: existing?.id || generateId(),
      order: i + 1,
      heading,
      content,
      visualPrompt: existing?.visualPrompt,
      duration: existing?.duration || 30,
    };
  });
}

function generateSrtFromEntries(entries: SubtitleEntry[]): string {
  return entries
    .map((e, i) => {
      const start = formatSrtTime(e.startTime);
      const end = formatSrtTime(e.endTime);
      return `${i + 1}\n${start} --> ${end}\n${e.text}`;
    })
    .join("\n\n");
}

function generateVttFromEntries(entries: SubtitleEntry[]): string {
  return `WEBVTT\n\n${entries
    .map((e) => {
      const start = formatSrtTime(e.startTime);
      const end = formatSrtTime(e.endTime);
      return `${start} --> ${end}\n${e.text}`;
    })
    .join("\n\n")}`;
}

function formatSrtTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);
  return `${h.toString().padStart(2, "0")}:${m.toString().padStart(2, "0")}:${s
    .toString()
    .padStart(2, "0")},${ms.toString().padStart(3, "0")}`;
}